language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  #- "sudo apt-get install libyaml-dev"

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: "nosetests -s -v --tc-file ./tests/nosetest.cfg"
