language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - "pip install nose"
    - "python setup.py install"
# command to run tests
script: "nosetests -s -v"
