language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - "pip install nose"
    - "pip install nose-testconfig"
    - "python setup.py develop"
# command to run tests
script: "nosetests -s -v --tc-file ./tests/nosetests.cfg"
